# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"go-web-api"},"name":"go-web-api","namespace":"default"},"spec":{"replicas$
  creationTimestamp: "2019-07-14T23:58:51Z"
  generation: 1
  labels:
    app: go-web-api
  name: go-web-api
  namespace: default
  resourceVersion: "39697"
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/go-web-api
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: go-web-api
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: go-web-api
