# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app":"go-web-api"},"name":"go-web-api","namespace":"default"},"spec":$
  creationTimestamp: "2019-07-14T23:59:01Z"
  labels:
    app: go-web-api
  name: frontend
  namespace: default
  resourceVersion: "40321"
  selfLink: /api/v1/namespaces/default/services/go-web-api
spec:
  clusterIP: 10.245.67.51
  externalTrafficPolicy: Cluster
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: go-web-api
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:

