apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-muxing-api
spec:
  selector:
    matchLabels:
      app: go-muxing-api
      tier: backend
      track: stable
  replicas: 2
  template:
    metadata:
      labels:
        app: go-muxing-api
        tier: backend
        track: stable
    spec:
      containers:
        - name: go-muxing-api
          image: "craigderington/go-muxing-api:latest"
          ports:
            - name: http
              containerPort: 8080
