apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-go-web
spec:
  selector:
    matchLabels:
      app: simple-go-web
      tier: backend
      track: stable
  replicas: 3
  template:
    metadata:
      labels:
        app: simple-go-web
        tier: backend
        track: stable
    spec:
      containers:
        - name: simple-go-web
          image: "us.gcr.io/fourth-gearing-136923/go-simple-http-server"
          ports:
            - name: http
              containerPort: 3000
